In [2]:
my_list = [1, 2, 3]

In [4]:
my_list

[1, 2, 3]

In [7]:
import numpy as np

In [10]:
arr = np.array(my_list)

In [12]:
arr

array([1, 2, 3])

In [14]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones(4)

array([1., 1., 1., 1.])

In [30]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [35]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.random.rand(5)

array([0.13697346, 0.04912769, 0.13414267, 0.46784989, 0.21285635])

In [39]:
np.random.rand(5,5)

array([[0.65953531, 0.41521324, 0.51235836, 0.60137526, 0.97473523],
       [0.41910816, 0.34660256, 0.1383001 , 0.00710575, 0.34495786],
       [0.16735503, 0.90414542, 0.90443797, 0.07453367, 0.6536526 ],
       [0.65370771, 0.15530461, 0.50300821, 0.74255622, 0.14203929],
       [0.50251434, 0.87072173, 0.04468185, 0.87190793, 0.54045863]])

In [40]:
np.random.randn(2,)

array([ 0.50088912, -0.55058492])

In [42]:
np.random.randn(4, 4)

array([[-0.06278138, -0.11248591, -1.20683437, -0.06879732],
       [-0.51579066, -0.25522332,  1.90804956,  0.0815287 ],
       [-0.01745141,  0.54733352, -1.49861891,  0.53554066],
       [-0.31579058,  0.69871621,  0.34783735,  1.00860987]])

In [50]:
np.random.randint(1, 100)

53

In [52]:
np.random.randint(1, 100, 10)

array([57, 58, 78, 51, 78, 86, 47, 74, 31, 35], dtype=int32)

In [54]:
np.random.randint(1, 10)

8

In [56]:
arr = np.arange(25)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [60]:
ran_arr = np.random.randint(0, 50, 10)

In [62]:
ran_arr

array([18, 21, 35,  5,  8, 38,  6, 33, 23, 48], dtype=int32)

In [64]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
ran_arr

array([18, 21, 35,  5,  8, 38,  6, 33, 23, 48], dtype=int32)

In [68]:
ran_arr.max()

np.int32(48)

In [70]:
ran_arr.min()

np.int32(5)

In [72]:
ran_arr

array([18, 21, 35,  5,  8, 38,  6, 33, 23, 48], dtype=int32)

In [74]:
ran_arr.argmax()

np.int64(9)

In [76]:
ran_arr.argmin()

np.int64(3)

In [78]:
ran_arr.shape

(10,)

In [80]:
arr= arr.reshape(5,5)

In [82]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [85]:
arr.dtype

dtype('int64')

In [87]:
from numpy.random import randint

In [88]:
randint(2, 10)

6