In [2]:
import numpy as np

In [4]:
arr = np.arange(0, 11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[9]

np.int64(9)

In [10]:
arr[-1]

np.int64(10)

In [12]:
arr[1:5]

array([1, 2, 3, 4])

In [14]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [16]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [18]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [20]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [22]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [24]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [26]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [28]:
arr[0:5] = 100

In [29]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [31]:
arr = np.arange(0, 11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
slice_of_arr = arr[0:6]

In [36]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [38]:
slice_of_arr[:] = 99

In [40]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [42]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [44]:
arr_copy = arr.copy()

In [46]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [47]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [49]:
arr_copy[:] = 100

In [51]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [52]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])