In [1]:
import numpy as np

In [3]:
arr_2d = np.array([[5, 10, 15], [20, 25, 20], [35, 40, 45]])

In [5]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 20],
       [35, 40, 45]])

In [11]:
arr_2d[0][0]

np.int64(5)

In [13]:
arr_2d[0]

array([ 5, 10, 15])

In [15]:
arr_2d[1][1]

np.int64(25)

In [17]:
arr_2d[2][1]

np.int64(40)

In [19]:
arr_2d[2, 1]

np.int64(40)

In [20]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 20],
       [35, 40, 45]])

In [22]:
arr_2d[2, 0]

np.int64(35)

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 20],
       [35, 40, 45]])

In [26]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 20]])

In [28]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 20]])

In [31]:
arr_2d[:1, 2:]

array([[15]])

In [33]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 20],
       [35, 40, 45]])

In [35]:
arr_2d[1]

array([20, 25, 20])

In [37]:
arr_2d[0]

array([ 5, 10, 15])

In [42]:
arr_2d[0, :3]

array([ 5, 10, 15])

In [47]:
arr_2d[1:]

array([[20, 25, 20],
       [35, 40, 45]])

In [49]:
arr =  np.arange(1,11)

In [51]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr > 5

In [56]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [57]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [59]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [61]:
arr[arr < 3]

array([1, 2])

In [63]:
arr_2d = np.arange(50).reshape(5, 10)

In [65]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [102]:
# [[25,26],[35,36]]
arr_2d[2:, :7][:2, 5:]

array([[25, 26],
       [35, 36]])

In [128]:
arr_2d[2:4, 5:7]

array([[25, 26],
       [35, 36]])